export async function GET() {
    const tours = [
        {
            id: 1,
            title: "Phi Phi, Khai Islands Tour with Speedboat Full Day",
            location: "Rassada Pier",
            price: 1400,
            oldPrice: 1820,
            discount: 30,
            rating: 4.3,
            reviews: 20,
            image: "/cover.jpg",
            vehicle: "Speedboat",
            theme: "Island Tour",
            features: ["Transfer", "Halal Food"],
            activity: ["Swimming", "Snorkeling"],
            groupSize: Math.floor(Math.random() * 10) + 1
        },
        {
            id: 2,
            title: "James Bond Island & Phang Nga Bay Tour",
            location: "Phuket Marina",
            price: 1200,
            oldPrice: 1500,
            discount: 20,
            rating: 4.7,
            reviews: 35,
            image: "/b1.jpg",
            vehicle: "Speedboat",
            theme: "Island Tour",
            features: ["Transfer", "Vegetarian Food"],
            activity: ["Swimming", "Running"],
            groupSize: Math.floor(Math.random() * 10) + 1
        },
        {
            id: 3,
            title: "Luxury Yacht Tour in the Maldives",
            location: "Malé City",
            price: 3200,
            oldPrice: 4000,
            discount: 20,
            rating: 4.9,
            reviews: 25,
            image: "/yat.jpg",
            vehicle: "Yacht",
            theme: "Local Tour",
            features: ["Halal Food", "Vegetarian Food"],
            activity: ["Swimming"],
            groupSize: Math.floor(Math.random() * 10) + 1
        },
        {
            id: 4,
            title: "Kruger Safari Experience",
            location: "Kruger Park Gate",
            price: 2200,
            oldPrice: 2700,
            discount: 18,
            rating: 4.5,
            reviews: 50,
            image: "/safari.jpg",
            vehicle: "Safari",
            theme: "Safari",
            features: ["Transfer"],
            activity: ["Running"],
            groupSize: Math.floor(Math.random() * 10) + 1
        },
        {
            id: 5,
            title: "Iceland Golden Circle Tour",
            location: "Reykjavík",
            price: 1800,
            oldPrice: 2200,
            discount: 18,
            rating: 4.6,
            reviews: 30,
            image: "/golden.webp",
            vehicle: "Tour Bus",
            theme: "Local Tour",
            features: ["Vegetarian Food"],
            activity: ["Swimming"],
            groupSize: Math.floor(Math.random() * 10) + 1
        },
        {
            id: 6,
            title: "Speedcatamaran Snorkeling Adventure",
            location: "Great Barrier Reef",
            price: 2500,
            oldPrice: 3000,
            discount: 16,
            rating: 4.8,
            reviews: 40,
            image: "/yat.jpg",
            vehicle: "Speedcatamaran",
            theme: "Island Tour",
            features: ["Transfer", "Halal Food"],
            activity: ["Snorkeling"],
            groupSize: Math.floor(Math.random() * 10) + 1
        },
        {
            id: 7,
            title: "Local Island Hopping by Yacht",
            location: "Bahamas",
            price: 2900,
            oldPrice: 3500,
            discount: 17,
            rating: 4.7,
            reviews: 28,
            image: "/b1.jpg",
            vehicle: "Yacht",
            theme: "Island Tour",
            features: ["Transfer", "Vegetarian Food"],
            activity: ["Swimming", "Running"],
            groupSize: Math.floor(Math.random() * 10) + 1
        },
        {
            id: 8,
            title: "Red Sea Snorkeling Adventure",
            location: "Hurghada, Egypt",
            price: 1600,
            oldPrice: 2000,
            discount: 20,
            rating: 4.6,
            reviews: 22,
            image: "/Boro.jpeg",
            vehicle: "Speedboat",
            theme: "Island Tour",
            features: ["Transfer", "Halal Food"],
            activity: ["Snorkeling"],
            groupSize: Math.floor(Math.random() * 10) + 1
        },
        {
            id: 9,
            title: "Amazon Rainforest Safari",
            location: "Manaus, Brazil",
            price: 2700,
            oldPrice: 3200,
            discount: 15,
            rating: 4.5,
            reviews: 37,
            image: "/amazon-safari.jpg",
            vehicle: "Safari",
            theme: "Safari",
            features: ["Transfer"],
            activity: ["Running", "Swimming"],
            groupSize: Math.floor(Math.random() * 10) + 1
        },
        {
            id: 10,
            title: "Maldivian Catamaran Experience",
            location: "Maldives",
            price: 3100,
            oldPrice: 3800,
            discount: 18,
            rating: 4.9,
            reviews: 30,
            image: "/maldives-catamaran.jpg",
            vehicle: "Catamaran",
            theme: "Local Tour",
            features: ["Vegetarian Food"],
            activity: ["Swimming", "Snorkeling"],
            groupSize: Math.floor(Math.random() * 10) + 1
        }
    ];

    return Response.json(tours);
}
